package coursera;

public class MainCodobCount {

	public static void main(String[] args) {
		CodonCount cc = new CodonCount();
/*		String input = "CGTTCAAGTTCAA";
		String input2 = "CCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACC"
				+ "AGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTC"
				+ "AGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTC"
				+ "AGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTC"
				+ "AGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTCAACCAGTTAGTTC"
				+ "AACCAGTTAGTTCAACCAGTTAGTTCAA";
		System.out.println(input);
		cc.buildCodonMap(2, input);
		cc.printHashDna();
		System.out.println("getMostCommonCodon = " + cc.getMostCommonCodon());
		cc.printCodonCounts(11, 11);*/
		
		cc.tester(6, 8);

	}

}
